### ISSUE TITLE
C# System.DllNotFoundException (k4a.dll)

### ISSUE THREAD

**Issue by TheRealAndreas** [microsoft/Azure-Kinect-Sensor-SDK#1534]
**Describe the bug**
On some PC's the .dll refuses to load.
Exact same program works on most of our pc's but once in a while we will encounter a machine where it just doesn't work.
So far we have just changed the PC when it for some reason refuses to work.
But now we have experienced the program working before a windows update, and then refusing to load the dll after a successful windows update.

**To Reproduce**
* Create a new C# console application.
* Add Microsoft.Azure.Kinect.Sensor nuget package v1.4.1
* Change platform to x64
* Add code:
```
static void Main(string[] args)
{
      Microsoft.Azure.Kinect.Sensor.Device.GetInstalledCount();
      Console.WriteLine("Press any key to exit...");
      Console.ReadKey();
}
```
* Run compiled program.

**Expected behavior**
A console window with the message "Press any key to exit..."

**Actual behavior**
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'k4a': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
  at Microsoft.Azure.Kinect.Sensor.NativeMethods.k4a_device_get_installed_count()
  at AzureKinectMissingExample.Program.Main(String[] args)

**Logs**
Application: AzureKinectMissingExample.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException
   at Microsoft.Azure.Kinect.Sensor.NativeMethods.k4a_device_get_installed_count()
   at AzureKinectMissingExample.Program.Main(System.String[])

**Desktop (please complete the following information):**
- OS with Version:
Edition	Windows 10 Pro
Version	20H2
Installed on	‎3/‎16/‎2021
OS build	19042.868
Experience	Windows Feature Experience Pack 120.2212.551.0

 - SDK Version:  1.4.1
 - Firmware version:  No kinect needed to provoke the error.

**Additional context**
So far we have just changed the PC when it for some reason refuses to work.
But now we have experienced the program working before a windows update, and then refusing to load the dll after a successful windows update.

**Comment by TheRealAndreas** [comment]
This code produces the exact same error. 
Works on same pc that the other code works on and fails on the same pc's that the other code fails on.
```
class Program
    {
        static void Main(string[] args)
        {
            k4a_device_get_installed_count();
            Console.WriteLine("Press any key to exit...");
            Console.ReadKey();
        }

        [DllImport("k4a.dll", CharSet = CharSet.Auto)]
        public static extern int k4a_device_get_installed_count();
    }
```
Could it be that the k4a.dll is trying to load some .dll that is delivered with windows but is somehow damaged on a few PC's?
And how could I identify the faulty dll in that case?

**Comment by TheRealAndreas** [comment]
Using this lovely tool: http://www.dependencywalker.com/
And running it on faulty machine and a healthy machine and comparing the results I have found, that the faulty machine is missing:
MSVCP140.dll and VCRUNTIME140.dll

Downloading and installing the following package resolved the issue.  
https://www.microsoft.com/en-us/download/details.aspx?id=48145

I do however feel that the error message could have been a little clearer.

# Update
Ok I jumped the gun a bit... It did solve the issue on that specific PC, but on another PC with same DllNotFoundException..
Both MSVCP140.dll and VCRUNTIME140.dll was intact, and reinstalling the c++ redis did not help with the problem..

**Comment by TheRealAndreas** [comment]
For anyone stumbling upon this ticket.
I ended up getting the issue resolved on troublesome systems by installing:
**c++ redistributable 2015**
And
**c++ redistributable 2019**
Both seems to be needed, and sometimes included on PC's and sometimes not... I guess it depends on the vendor supplying the machines.
